In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from google.colab import drive
import matplotlib.pyplot as plt

In [3]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
df_people_2101 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202101.csv', encoding='cp949') 
df_people_2102 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202102.csv', encoding='cp949') 
df_people_2103 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202103.csv', encoding='cp949') 
df_people_2104 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202104.csv', encoding='cp949') 
df_people_2105 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202105.csv', encoding='cp949') 
df_people_2106 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202106.csv', encoding='cp949') 
df_people_2107 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202107.csv', encoding='cp949')

In [5]:
df_people_2108 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202108.csv',index_col=False)

In [6]:
df_people_2109 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202109.csv',index_col=False) 
df_people_2110 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202110.csv',index_col=False) 
df_people_2111 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202111.csv',index_col=False) 
df_people_2112 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202112.csv',index_col=False)

In [8]:
df_people_2201 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202201.csv', encoding='cp949') 
df_people_2202 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202202.csv',index_col=False) 
df_people_2203 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202203.csv',index_col=False) 
df_people_2204 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202204.csv',index_col=False) 
df_people_2205 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202205.csv',index_col=False) 
df_people_2206 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202206.csv',index_col=False)

In [9]:
df_people_2207 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202207.csv', encoding='cp949') 
df_people_2208 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202208.csv',index_col=False) 
df_people_2209 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202209.csv',index_col=False) 
df_people_2210 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202210.csv',index_col=False) 
df_people_2211 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202211.csv',index_col=False) 
df_people_2212 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/팀과제/LOCAL_PEOPLE_DONG_202212.csv',index_col=False)

In [10]:
df_people = pd.concat([df_people_2101, df_people_2102, df_people_2103,df_people_2104, df_people_2105,df_people_2106,df_people_2107,df_people_2108,df_people_2109,df_people_2110,df_people_2111,df_people_2112,df_people_2201, df_people_2202, df_people_2203,df_people_2204, df_people_2205,df_people_2206,df_people_2207,df_people_2208,df_people_2209,df_people_2210,df_people_2211,df_people_2212 ],sort=False)

In [11]:
df_people.describe()

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
count,7.428480e+06,7.428480e+06,7.428480e+06,7.428480e+06,7.428480e+06,7.428480e+06,7.428480e+06,7.428480e+06,7.428480e+06,7.428480e+06,...,7.428480e+06,7.428480e+06,7.428480e+06,7.428480e+06,7.428480e+06,7.428480e+06,7.428480e+06,7.428480e+06,7.428480e+06,7.428480e+06
mean,2.021567e+07,1.150000e+01,1.143320e+07,2.433659e+04,8.393468e+02,4.506194e+02,6.295803e+02,7.437553e+02,9.607530e+02,9.295345e+02,...,1.065303e+03,9.921255e+02,1.101473e+03,9.651483e+02,1.029030e+03,8.798247e+02,9.350399e+02,8.100394e+02,6.241006e+02,1.562136e+03
std,5.011889e+03,6.922187e+00,1.916679e+05,1.343475e+04,5.682324e+02,3.354604e+02,4.638965e+02,5.647764e+02,8.076286e+02,8.051354e+02,...,9.717190e+02,8.051152e+02,7.528481e+02,6.080195e+02,5.851519e+02,4.332449e+02,4.361162e+02,3.691268e+02,2.819426e+02,6.930500e+02
min,2.021010e+07,0.000000e+00,1.111052e+07,1.102867e+03,0.000000e+00,0.000000e+00,1.334720e+01,1.599630e+01,1.310400e+01,1.307940e+01,...,1.227350e+01,1.697490e+01,1.853340e+01,3.160760e+01,4.715150e+01,2.146540e+01,1.770750e+01,1.412710e+01,1.687260e+01,3.300060e+01
25%,2.021070e+07,5.750000e+00,1.126065e+07,1.581637e+04,4.710186e+02,2.360073e+02,3.456156e+02,4.119711e+02,4.908351e+02,4.831191e+02,...,5.217009e+02,5.381875e+02,6.475449e+02,5.774920e+02,6.416391e+02,5.816033e+02,6.285177e+02,5.519063e+02,4.251520e+02,1.084050e+03
50%,2.021567e+07,1.150000e+01,1.144062e+07,2.161105e+04,7.086048e+02,3.716148e+02,5.217976e+02,6.123170e+02,7.632103e+02,7.415521e+02,...,8.203286e+02,7.936649e+02,9.147562e+02,8.118855e+02,8.913754e+02,7.950874e+02,8.621693e+02,7.566854e+02,5.869411e+02,1.459031e+03
75%,2.022070e+07,1.725000e+01,1.159814e+07,3.005565e+04,1.068008e+03,5.561566e+02,7.793925e+02,8.821158e+02,1.167446e+03,1.112847e+03,...,1.304248e+03,1.200921e+03,1.353666e+03,1.195374e+03,1.266963e+03,1.093320e+03,1.171089e+03,1.009544e+03,7.759498e+02,1.930671e+03
max,2.022123e+07,2.300000e+01,1.174070e+07,3.448004e+05,1.898909e+04,9.168379e+03,1.543124e+04,1.499340e+04,1.803278e+04,1.574283e+04,...,2.107690e+04,1.644649e+04,1.665338e+04,1.492600e+04,1.197778e+04,8.541623e+03,8.119866e+03,5.625711e+03,3.687504e+03,8.397896e+03

In [12]:
# reset_index(drop=True)
df_people.reset_index(drop=True)

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20210101,0,11110515,14473.8890,504.7535,321.6298,474.2765,624.4867,507.3616,405.9607,...,424.0524,459.3872,534.8354,673.7167,746.3401,609.6886,590.1671,422.7630,339.8220,1138.9208
1,20210101,0,11110530,13299.5313,364.9421,162.1967,254.0620,318.9359,449.9919,419.8851,...,459.9216,537.1230,667.1788,565.2750,603.2522,522.3540,543.4003,447.2674,363.1686,1138.6352
2,20210101,0,11110550,15518.3772,418.3329,324.3693,380.5245,529.5754,470.6277,415.8823,...,417.9814,448.0938,621.1825,636.9613,840.1881,692.5841,693.3884,630.9412,421.9502,1456.3029
3,20210101,0,11110600,5108.9481,122.7939,86.6778,90.4754,203.9829,137.2541,124.3374,...,127.1385,180.1318,183.2139,268.8835,268.7073,247.4089,227.3631,163.6567,135.4872,406.3143
4,20210101,0,11110700,7907.7246,224.1087,106.2126,153.8756,194.7256,272.8423,315.6010,...,280.9285,279.1961,309.0617,316.6311,371.2800,370.3215,377.7498,258.4794,213.1911,532.8069
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7428475,20221231,23,11740550,26849.5654,2351.0068,1214.8337,937.6079,456.3894,498.5714,472.1622,...,513.0224,561.7293,1099.6503,1217.8158,1274.9191,851.5014,816.0413,778.8732,640.6550,1236.6337
7428476,20221231,23,11590540,20025.0040,1031.9551,378.5519,384.2442,613.5671,790.2585,713.5261,...,746.3391,713.8543,1026.2784,819.3403,749.9114,689.6776,820.0387,676.9692,602.1882,1293.3497
7428477,20221231,23,11470630,16125.0930,526.2720,583.5859,839.0280,368.6007,365.4509,305.8051,...,359.1490,348.7186,485.3043,775.2054,876.9643,721.4776,639.9144,509.0424,404.5792,937.8374
7428478,20221231,23,11710540,14964.0371,658.0712,375.2026,330.4875,294.3431,351.6816,401.5746,...,372.0913,415.5257,593.9416,580.5089,608.0485,651.5841,633.4928,609.3532,509.4529,1173.0780
7428479,20221231,23,11410520,15880.9395,531.5645,267.4092,424.2795,526.1068,397.8731,408.0758,...,435.6255,513.5928,679.8988,688.8782,767.0536,686.4816,732.0469,584.9260,461.1601,1265.5130

In [13]:
df_people.to_csv('./df_people.csv',encoding ='utf-8')

In [ ]:
df_people.describe()

In [ ]:
df_people.info()

In [ ]:
# df['DOB']=pd.to_datetime(df['DOB'].astype(str), format='%m/%d/%Y')